### PR TITLE
Fix README.md RTL

### PR DESCRIPTION
**Pull request by alifarazz**
I added some HTML tags to `README.md` so that the Farsi text would be rendered RTL.
I also added a `$` before the shell commands.

### CODE REVIEW

**Comment by alifarazz** [comment]
Though before any merging happens, what do you think about removing all the `sudo` from the shell commands and appending a `#` before them to convey that fact that they must be executed with root privileges?
If you're ok with this, I'd like to submit these modifications in the current PR too.

**Comment by kiamazi** [comment]
I think use a `U+202F` character at the beginning of each RTL line is a better way than using `<div dir="rtl">` to force different markdown displayers to show those lines correctly.

**Comment by alifarazz** [comment]
I added a `U+202F` at the begining of each RTL line but it doesn't seem to help.

**Comment by alifarazz** [comment]
@kiamazi What do you think?

**Comment by kiamazi** [comment]
‫معذرت، یه مدت زیاد آنلاین نمیشم. ولی فایل readme اول هر خطش کاراکتر راست چین بود از اول!
اگر بشه کل فایل رو از اول نوشت و یه راهنمای بهتر درست کرد فکر کنم بهتر باشه، اگر بتونید همچین زحمتی بکشید خیلی عالی میشه

**Pull request closed without merging**
